### ISSUE TITLE
Scroll Bars

### ISSUE THREAD

**Issue by M4598bm** [M4598bm/President#1]
I need scroll bars to be fixed. They already sort of exist and are on the right side of the page when there is a scroll, but they don't fully work. Like a normal scroll bar, it needs to be proportional to the size of the screen, not appear when the amount of data is less than the screen, and scroll all the way to the bottom.

The code that needs to be fixed is in Screen from lines 780 -790. There are instructions. To run it, press the Congress button and then press the Talk to Legislators button. There is the screen that you should use. To make it a larger screen add NY to the search queue.

**Comment by RychardHunt** [comment]
Update this shit. Comment all the variables.

**Comment by M4598bm** [comment]
idk I just gave it to you thomas in case you have time, don't worry about it though, it's kind of unclear. It's just sort of off still and I think it's because the length of the bar itself isn't taken into account. I don't fully understand it though, tbh.
